# Generated by Django 4.2.4 on 2023-08-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransferOrder",
            fields=[
                ("amount", models.DecimalField(decimal_places=2, max_digits=19)),
                ("sender_account", models.IntegerField()),
                ("receiver_account", models.IntegerField()),
                (
                    "transaction_hash",
                    models.UUIDField(primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
